Repository Hani-home/HaniHome_BE, pull requests merged in 2025-07, with the labels that each got.

#166 [FEAT]#163 매물 suburb 필터링 기능 추가 및 뷰잉옵션아이템 추가
  src/main/java/org/hanihome/hanihomebe/item/application/init/ScopeInitializer.java
  src/main/java/org/hanihome/hanihomebe/item/application/init/ViewingItemInitializer.java
  src/main/java/org/hanihome/hanihomebe/item/domain/CategoryCode.java
  src/main/java/org/hanihome/hanihomebe/property/repository/PropertySearchRepositoryImpl.java
  src/main/java/org/hanihome/hanihomebe/property/web/dto/request/PropertySearchConditionDTO.java
  src/test/java/org/hanihome/hanihomebe/property/application/service/PropertySearchServiceTest.java
Labels: feature, refactor

#170 Feature/#169 interest region
  src/main/java/org/hanihome/hanihomebe/global/aop/exception/ExceptionNotificationAspect.java
  src/main/java/org/hanihome/hanihomebe/global/response/wrapper/GlobalResponseWrapper.java
  src/main/java/org/hanihome/hanihomebe/member/service/MemberService.java
  src/main/java/org/hanihome/hanihomebe/member/web/MemberController.java
  src/main/java/org/hanihome/hanihomebe/member/web/dto/MemberDetailResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/member/web/dto/MemberMyPageDTO.java
  src/main/java/org/hanihome/hanihomebe/member/web/dto/MemberResponseContext.java
  src/main/java/org/hanihome/hanihomebe/member/web/dto/MemberResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/security/auth/web/controller/AuthController.java
  src/main/java/org/hanihome/hanihomebe/verification/service/VerificationService.java
  src/test/java/org/hanihome/hanihomebe/property/application/service/VerificationServiceTest.java
Labels: feature

#174 [FIX]#173 뷰잉, 매물 옵션아이템 수정 안되는 오류 해결
  src/main/java/org/hanihome/hanihomebe/item/application/OptionItemConverter.java
  src/main/java/org/hanihome/hanihomebe/item/application/converter/OptionItemConverter.java
  src/main/java/org/hanihome/hanihomebe/item/application/converter/OptionItemConverterForProperty.java
  src/main/java/org/hanihome/hanihomebe/item/application/converter/OptionItemConverterForViewing.java
  src/main/java/org/hanihome/hanihomebe/property/application/service/PropertyConversionService.java
  src/main/java/org/hanihome/hanihomebe/property/application/service/PropertyService.java
  src/main/java/org/hanihome/hanihomebe/property/domain/Property.java
  src/main/java/org/hanihome/hanihomebe/property/domain/item/PropertyOptionItem.java
  src/main/java/org/hanihome/hanihomebe/property/web/dto/request/PropertyPatchRequestDTO.java
  src/main/java/org/hanihome/hanihomebe/viewing/application/service/ViewingConversionService.java
  src/main/java/org/hanihome/hanihomebe/viewing/application/service/ViewingService.java
  src/main/java/org/hanihome/hanihomebe/viewing/domain/Viewing.java
  src/main/java/org/hanihome/hanihomebe/viewing/domain/ViewingOptionItem.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/controller/ViewingController.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/converter/ViewingDateWithProfileImageConverter.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/converter/ViewingDefaultConverter.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/converter/context/ViewingConvertContext.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/dto/ViewingResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/wishlist/application/service/PropertyWishTargetService.java
Labels: hotfix

#186 [FIX] 게스트 모드(token이 없을 시)일 때 필터 오류 해결
  src/main/java/org/hanihome/hanihomebe/global/utility/SecurityContextUtils.java
  src/main/java/org/hanihome/hanihomebe/security/auth/application/filter/JwtAuthenticationFilter.java
  src/main/java/org/hanihome/hanihomebe/security/config/SecurityConfig.java
Labels: bug, hotfix

#191 [REFACTOR] 뷰잉 DTO 필드 추가
  src/main/java/org/hanihome/hanihomebe/security/config/SecurityConfig.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/converter/ViewingDateWithPropertyConverter.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/dto/ViewingDateWithPropertyDTO.java
Labels: refactor

#194 Feature/#193 cancel all viewings
  src/main/java/org/hanihome/hanihomebe/item/repository/OptionItemRepository.java
  src/main/java/org/hanihome/hanihomebe/property/application/service/PropertyService.java
  src/main/java/org/hanihome/hanihomebe/property/domain/vo/ShareInternalDetails.java
  src/main/java/org/hanihome/hanihomebe/property/web/controller/PropertyController.java
  src/main/java/org/hanihome/hanihomebe/property/web/dto/request/PropertyCompleteTradeDTO.java
  src/main/java/org/hanihome/hanihomebe/viewing/application/service/ViewingService.java
  src/main/java/org/hanihome/hanihomebe/viewing/domain/Viewing.java
  src/main/java/org/hanihome/hanihomebe/viewing/repository/CustomViewingRepository.java
  src/main/java/org/hanihome/hanihomebe/viewing/repository/CustomViewingRepositoryImpl.java
  src/main/java/org/hanihome/hanihomebe/viewing/repository/ViewingRepository.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/controller/ViewingController.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/dto/cancel/ViewingCancelRequestDTO.java
  src/main/java/org/hanihome/hanihomebe/viewing/web/dto/cancel/ViewingCancelResponseDTO.java
  src/test/java/org/hanihome/hanihomebe/property/application/service/PropertyServiceTest.java
Labels: feature, refactor

#196 [FIX]#195 숨김상태 매물 처리
  src/main/java/org/hanihome/hanihomebe/global/response/domain/ServiceCode.java
  src/main/java/org/hanihome/hanihomebe/global/utility/SecurityContextUtils.java
  src/main/java/org/hanihome/hanihomebe/property/application/service/PropertyService.java
  src/main/java/org/hanihome/hanihomebe/property/repository/PropertySearchRepositoryImpl.java
  src/main/java/org/hanihome/hanihomebe/property/web/controller/PropertyController.java
Labels: hotfix
