Repository Hani-home/HaniHome_BE, pull requests merged in 2025-08, with the labels that each got.

#206 [FIX] 임포트 수정
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryProperty.java
Labels: hotfix

#210 [FEAT] 임시저장 매물 전체, 상세 조회
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/application/TemporaryPropertyService.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryRentProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryShareProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/vo/temporaryDetails/TemporaryRentInternalDetails.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/vo/temporaryDetails/TemporaryShareInternalDetails.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/repository/TemporaryPropertyRepository.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/controller/TemporaryPropertyController.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporaryPropertyListResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporaryPropertyResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporaryRentPropertyResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporarySharePropertyResponseDTO.java
Labels: feature

#214 [REFACTOR]#213 매물 삭제 - 연관엔티티 삭제로직 수정
  src/main/java/org/hanihome/hanihomebe/property/application/service/PropertyService.java
  src/main/java/org/hanihome/hanihomebe/report/application/PropertyReportHandler.java
  src/main/java/org/hanihome/hanihomebe/report/application/ReportHandler.java
  src/main/java/org/hanihome/hanihomebe/report/repository/ReportRepository.java
  src/main/java/org/hanihome/hanihomebe/report/service/ReportService.java
Labels: feature, refactor

#215 [FIX]/#213 매물 삭제 시 - 연관 엔티티 삭제 로직 수정
  src/main/java/org/hanihome/hanihomebe/report/application/PropertyReportHandler.java
  src/main/java/org/hanihome/hanihomebe/report/application/ReportHandler.java
  src/main/java/org/hanihome/hanihomebe/report/repository/PropertyReportRepository.java
  src/main/java/org/hanihome/hanihomebe/report/service/ReportService.java
Labels: hotfix

#216 [REFACTOR] 매물 삭제 - 연관 엔티티 삭제 로직 중 Deal 추가
  src/main/java/org/hanihome/hanihomebe/deal/repository/DealRepository.java
  src/main/java/org/hanihome/hanihomebe/property/application/service/PropertyService.java
  src/main/java/org/hanihome/hanihomebe/viewing/application/service/ViewingService.java
Labels: refactor

#219 [FEAT] 중간 테이블 기반 찜하기
  src/main/java/org/hanihome/hanihomebe/property/application/service/PropertyConversionService.java
  src/main/java/org/hanihome/hanihomebe/property/application/service/PropertyService.java
  src/main/java/org/hanihome/hanihomebe/property/domain/Property.java
  src/main/java/org/hanihome/hanihomebe/property/web/dto/response/summary/RentPropertySummaryDTO.java
  src/main/java/org/hanihome/hanihomebe/wishItem/domain/PropertyWishItem.java
  src/main/java/org/hanihome/hanihomebe/wishItem/domain/WishItem.java
  src/main/java/org/hanihome/hanihomebe/wishItem/repository/PropertyWishItemRepository.java
  src/main/java/org/hanihome/hanihomebe/wishItem/service/PropertyWishItemService.java
  src/main/java/org/hanihome/hanihomebe/wishItem/web/PropertyWishItemController.java
Labels: enhancement, feature

#220 [fix] service 함수 파라미터 순서 수정
  src/main/java/org/hanihome/hanihomebe/wishItem/service/PropertyWishItemService.java
  src/main/java/org/hanihome/hanihomebe/wishItem/web/PropertyWishItemController.java
Labels: hotfix

#222 [REFACTOR] 프론트 UI에 맞게 DTO 필드 수정
  src/main/java/org/hanihome/hanihomebe/verification/service/VerificationService.java
  src/main/java/org/hanihome/hanihomebe/verification/web/VerificationController.java
  src/main/java/org/hanihome/hanihomebe/verification/web/converter/VerificationConverter.java
  src/main/java/org/hanihome/hanihomebe/verification/web/dto/VerificationAdminSummaryResponseDTO.java
Labels: refactor

#223 [FEAT] 관리자 신원인증 상세조회 컨트롤러 구현
  src/main/java/org/hanihome/hanihomebe/verification/service/VerificationService.java
  src/main/java/org/hanihome/hanihomebe/verification/web/VerificationController.java
  src/main/java/org/hanihome/hanihomebe/verification/web/converter/VerificationConverter.java
  src/main/java/org/hanihome/hanihomebe/verification/web/dto/VerificationAdminSummaryResponseDTO.java
Labels: feature, hotfix

#244 [REFACTOR] 관리자 신원인증 컨트롤러 분리
  src/main/java/org/hanihome/hanihomebe/verification/web/VerificationAdminController.java
  src/main/java/org/hanihome/hanihomebe/verification/web/VerificationController.java
Labels: refactor

#248 [REFACTOR] PROPERTY와 응답 포맷 맞춤
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryRentProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/vo/TemporaryCostDetails.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/vo/TemporaryLivingConditions.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/vo/TemporaryMoveInInfo.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporaryRentPropertyResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporarySharePropertyResponseDTO.java
Labels: refactor

#250 [CHORE]/#242 logging infra
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  infra/logging-monitoring/fluent-bit/fluent-bit.dev.conf
  infra/logging-monitoring/fluent-bit/fluent-bit.prod.conf
  infra/logging-monitoring/fluent-bit/parsers.conf
  infra/logging-monitoring/grafana/provisioning/datasources/datasources.yml
  infra/logging-monitoring/loki/local-config.dev.yml
  infra/logging-monitoring/loki/local-config.prod.yml
  infra/logging-monitoring/prometheus/prometheus.yml.template
  infra/logging-monitoring/prometheus/rules/alert-rules.yml
Labels: chore

#253 [FEAT] 임시저장 시 매물 단계 저장 및 반환
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/application/TemporaryPropertyService.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryPropertyStepStatus.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryRentProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryShareProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/create/TemporaryPropertyCreateRequestDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/create/TemporaryRentPropertyCreateRequestDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/create/TemporarySharePropertyCreateRequestDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporaryPropertyListResponseDTO.java
Labels: feature

#255 [REFACTOR]#254 임시 매물
  build.gradle
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/application/TemporaryPropertyService.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryRentProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/domain/TemporaryShareProperty.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/create/TemporaryPropertyCreateRequestDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/create/TemporaryRentPropertyCreateRequestDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/create/TemporarySharePropertyCreateRequestDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporaryRentPropertyResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporarySharePropertyResponseDTO.java
Labels: refactor

#257 [FIX] 임시저장 매물 반환타입 수정
  src/main/java/org/hanihome/hanihomebe/global/response/domain/ServiceCode.java
  src/main/java/org/hanihome/hanihomebe/security/auth/application/filter/JwtAuthenticationFilter.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/application/TemporaryPropertyService.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/controller/TemporaryPropertyController.java
Labels: hotfix

#259 [REFACTOR]#258 임시매물의 timeslots 개수를 3개로 고정
  src/main/java/org/hanihome/hanihomebe/property/domain/vo/TimeSlot.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporaryRentPropertyResponseDTO.java
  src/main/java/org/hanihome/hanihomebe/temporaryProperty/web/dto/response/TemporarySharePropertyResponseDTO.java
Labels: refactor
